### ISSUE TITLE
discord bot notifications not sending completed/summary

### ISSUE THREAD

**Issue by whur** [auanasgheps/snapraid-aio-script#55] opened 2023-02-07 04:47 UTC
I setup the discord bot for notifications and I get the "script started" notification but not any completed notifications or summaries. Am I missing something?

**Comment by auanasgheps** [comment] 2023-02-09 11:10
I just made a test and it's working perfectly fine.

![image](https://user-images.githubusercontent.com/20586878/217796680-df1faf86-5b15-4bef-8866-76e49609ed5b.png)

**Comment by whur** [comment] 2023-02-09 17:29
This is all I get, it's a fresh install and i'm unsure what I missed

<img width="628" alt="Capture" src="https://user-images.githubusercontent.com/5874866/217891253-afb1591d-dae2-4a3b-ab83-2fa491349016.PNG">

**Comment by whur** [comment] 2023-02-11 19:42
switched to email

**Comment by auanasgheps** [comment] 2023-02-12 00:46
I'm sorry it's not working for you, but I really don't know what's going on.

**Comment by whur** [comment] 2023-02-12 03:31
That's alright, I'm trying to move off discord anyways for notifications.

**Comment by tehniemer** [comment] 2023-02-12 03:45
Telegram bots are working great for me.

**Comment by auanasgheps** [comment] 2023-02-12 10:53
And I'm about to increase the information sent to Telegram :)

**Comment by firasdib** [comment] 2023-06-29 07:06
I'm having the same issue on discord, btw :)

**Comment by auanasgheps** [comment] 2023-07-25 09:13
Hi, just a quick comment on this: Discord is very picky when sending data, requires complex character escaping, instead Telegram just accepts the code as is. I'm facing a lot of issues with Discord when trying to do other things and I believe is the same issue of what you're seeing. I don't know how to fix so any contribution is welcome

**Comment by auanasgheps** [comment] 2023-07-26 09:58
Hey there, just pushed the changes! If you fancy, you can quickly try the dev branch, but do not use it in production yet. 

Please note that I was never able to replicate this specific problem, so hopefully I fixed it by making the Discord notifications more robust.

**Comment by firasdib** [comment] 2023-09-14 16:54
@auanasgheps Any ETA on the release of this :)?

**Comment by auanasgheps** [comment] 2023-09-14 17:37
> @auanasgheps Any ETA on the release of this :)?

Can you try the dev branch and confirm the fix? I never managed to reproduce it, but I changed the Discord logic.

I might push the release soon, since I've done everything I wanted :)

**Comment by firasdib** [comment] 2023-09-14 17:55
I'm not sure how to test it besides running it live on my server. If it's ready for that, I'd be happy to try it!

**Comment by auanasgheps** [comment] 2023-09-14 22:22
Yes that's what I mean. Please try and let me know if you get notifications.

**Comment by firasdib** [comment] 2023-09-15 14:17
Alright, I will try the dev version.

**Comment by firasdib** [comment] 2023-09-15 15:37
Alright, just ran it. It sent the smart log to the discord channel, but not the snap status, instead I see this error in the log:

```
curl: (22) The requested URL returned error: 400 
```

It's nice it gives a summary, but it should also include the duration.

Overall, nice improvement. I think using embeds in discord would look even better, with data more easily human readable and stylish.

**Comment by auanasgheps** [comment] 2023-09-18 13:07
@firasdib thanks for the feedback! Can you please tell exactly when do you get the error? Only for the Snap Status? 

> I think using embeds in discord would look even better
I have enabled code formatting for Snap Status and SMART and if it's what you mean. Would you like to have it for all messages?

**Comment by firasdib** [comment] 2023-09-18 14:11
Error is after the script sync is complete, and it tries to post things to discord.

I mean, instead of just dumping large text blocks, [embeds](https://discordjs.guide/popular-topics/embeds.html#embed-preview) can look a lot nicer.

**Comment by auanasgheps** [comment] 2023-09-18 15:09
Yeah, but what is actually posted to Discord?

Ok, I understand what you mean with embeds. It's tough for me, short term I won't be able to make it.

**Comment by firasdib** [comment] 2023-09-18 15:48
I see the smart log on discord, as well as the total amount of files processed. The array info nor run time is posted. Vänliga hälsningar / Best regards,Firas DibOn 18 Sep 2023, at 17:09, Oliver Cervera ***@***.***> wrote:﻿
Yeah, but what is actually posted to Discord?
Ok, I understand what you mean with embeds. It's tough for me, short term I won't be able to make it.

**Comment by Hilo4321** [comment] 2023-12-10 01:22
Just to have another data point, I came searching for this issue, and concur with @jack-mil. Same symptoms. When I populated the email address, I got the follow up message "[COMPLETED] DIFF + SYNC + SCRUB Jobs (SnapRAID on trainer)" upon completion.

**Comment by jack-mil** [comment] 2023-12-10 01:25
Forgot to update here. I switched to the dev branch where a lot of features and reorganization has happened. The notification system works correctly with those changes

**Comment by Hilo4321** [comment] 2023-12-10 01:47
I just tried it myself, and only get the script started message with 3.3-dev.

**Comment by jack-mil** [comment] 2023-12-10 19:10
> I just tried it myself, and only get the script started message with 3.3-dev.
> 
> EDIT: With the dev script, I get the 400 error at the very end.
> 
> I can't figure out how to format this inline so: https://paste.debian.net/1300667/

> `/usr/sbin/snapraid-aio-script-3.3-dev/snapraid-aio-script.sh: line 816: jq: command not found`

There is a new dependency, `jq` to format the json data properly. 
I began looking into using `jq` more comprehensivly to format embeds and make better use of the Discord webhook system. But then I found this https://github.com/firasdib/snapper and decided to switch since I am more familiar with Python and can more easily modify and contribute to that project. 
The features I can tell are missing is the ability to schedule scrubs at less frequency (every N runs) and the ability to pause/stop docker containers.

**Comment by auanasgheps** [comment] 2023-12-19 11:00
Hi, apologies for the delayed response.

@jack-mil thanks for reporting the dev branch works for you. I'm sorry you abandoned this script because of the language, but be assured this project is alive :)

I made my best to make the Discord logic stronger. It has some weird stuff going around, it's more complex than Telegram.

I am not aware of `jq` dependency. My testing is done on OMV 6 (which is Debian 11) and I did not need to install any jq package.  Also, jq is never mentioned in my script so I guess it's a dependency from something else. I guess you need to update your packages?

Since I got confirmation that my fix is fine, I'll be soon closing this issue.

**Comment by firasdib** [comment] 2023-12-19 11:11
@auanasgheps You could have a look at my snapraid script which has complex discord integration here: https://github.com/firasdib/snapper/blob/main/snapper.py#L111

**Comment by jack-mil** [comment] 2023-12-19 14:56
> I am not aware of `jq` dependency. My testing is done on OMV 6 (which is Debian 11) and I did not need to install any jq package. Also, jq is never mentioned in my script so I guess it's a dependency from something else. I guess you need to update your packages?

The `[jq`](https://jqlang.github.io/jq/) tool is definitely used every time the discord webhook is sent on the dev branch. See: [L816](https://github.com/auanasgheps/snapraid-aio-script/blob/928dfe6cfe8cf9b65b397410e88f8ddfa3f2b74d/snapraid-aio-script.sh#L816C45-L816C47). This filter chain seems to be done to sanitize and escape the input strings into json format

**Comment by Hilo4321** [comment] 2023-12-22 15:22
I was able to get 3.3dev to run by installing jq. It would not run without it. I was also able to get appropriate notifications in discord with it.

See this line from my paste above:

`/usr/sbin/snapraid-aio-script-3.3-dev/snapraid-aio-script.sh: line 816: jq: command not found`

**Comment by auanasgheps** [comment] 2023-12-22 17:46
Ok, will add it to the requirement list and also install it if not available.

**Comment by auanasgheps** [comment] 2024-01-23 10:48
Hi all,
I implemented a little fix suggested in #78 that should fix the Discord notification!
If you want to test it, it's in the dev branch.

**Comment by auanasgheps** [comment] 2024-02-15 16:02
Hi there, I'm closing this out as I think we've finally found the root cause and fixed it. 
I am planning for a release soon.

**Closed by auanasgheps** 2024-02-15 16:02 UTC
Labels: bug, wait for feedback
