### ISSUE TITLE
Email still sending after removing it

### ISSUE THREAD

**Issue by helangen** [auanasgheps/snapraid-aio-script#100] opened 2024-04-22 15:42 UTC
Hi,

Thanks for a great script. I noticed that I still receive emails even though I removed or put "" in the email in the config. I can't see that the email is stored somehere else so how do I make it stop? I have set up a webhook via Discord which I prefer.

**Comment by auanasgheps** [comment] 2024-04-23 09:34
Hi can you please check your config?

It should be:

```shell
EMAIL_ADDRESS=""
FROM_EMAIL_ADDRESS=""
```

**Comment by PhilDim1** [comment] 2024-04-23 16:15
Same here, actually

**Comment by GerardPolloRebozado** [comment] 2024-05-06 10:45
I just downloaded the script and set email as "" but I get error while running the script while trying to send email to "" and also say it didn't find the path to the mail bin

**Comment by auanasgheps** [comment] 2024-05-10 08:54
Hi all, sorry for the late reply.

I tried replicating the issue, but I did not get any email.

This is the test configuration:

```
EMAIL_ADDRESS=""
FROM_EMAIL_ADDRESS=""
```

Here's the output:

```
Email address is set. Sending email report to **** [Fri May 10 10:49:31 CEST 2024]
sendmail: fatal: (0): No recipient addresses found in message header
Can't send mail: sendmail process failed with error code 75

```

Yeah, it could be better, because the string "email address is set" is not correct. I'll look into this, but still, I did not receive any email.



> I just downloaded the script and set email as "" but I get error while running the script while trying to send email to "" and also say it didn't find the path to the mail bin

This is another issue: it means you're using a distro that does not have `mailx`. You have two options: you either install mailx or use another mail service via Notification Hooks.

**Comment by auanasgheps** [comment] 2024-05-10 09:16
Allright, I fixed the issue, it was quite simple. 

The fix is dev branch with the commit d2e5678 

Please let me know if it works. In my case the error message disappeared.

**Comment by PhilDim1** [comment] 2024-05-10 13:15
I ended up configuring a whole mail service in the interim, but removing my address in the config produced no errors. Thank you for this software, i'm really happy with it.

**Comment by helangen** [comment] 2024-05-11 08:33
Thx. I downloaded the new script now. I will test when it runs at 11:00. My issue was that I set an email initially and then removed it. After that I got this problem. It was not with a fresh run. I’ll give feedback ASAP

**Comment by helangen** [comment] 2024-05-11 19:57
Nope, still got an email

**Comment by auanasgheps** [comment] 2024-05-13 09:34
@helangen so you're facing another issue.
Please check the logs on the server.
Does it say it's sending the message to an email address?

**Comment by helangen** [comment] 2024-05-14 10:19
> @helangen so you're facing another issue. Please check the logs on the server. Does it say it's sending the message to an email address?

I downloaded a fresh script and just set the same parameters as I had previously. Tried running it again.

Which log? /var/log/snapraid.log or the mail log?

**Comment by helangen** [comment] 2024-05-15 05:34
Last run did not produce an email. This was after downloading the new script and config file.

**Comment by auanasgheps** [comment] 2024-05-15 07:48
That's good news, so it's sorted :)

**Comment by helangen** [comment] 2024-05-20 15:14
The dreaded emails just started up again. No changes to the config or script.

**Comment by auanasgheps** [comment] 2024-05-20 17:21
Please check /tmp/snapRAID.out and see if at the end of the log you get something like:

## Total time elapsed for SnapRAID: 0hrs 18min 2sec
Email address is set. Sending email report to **MYADDRESS@gmail.com** [Mon 20 May 12:25:03 CEST 2024]

**Comment by helangen** [comment] 2024-05-21 06:55
> Please check /tmp/snapRAID.out and see if at the end of the log you get something like:
> 
> ```
> ## Total time elapsed for SnapRAID: 0hrs 18min 2sec
> Email address is set. Sending email report to **MYADDRESS@gmail.com** [Mon 20 May 12:25:03 CEST 2024]
> ```

This is what I have in the output file:

## Total time elapsed for SnapRAID: 2hrs 6min 42sec
Email address is set. Sending email report to **** [ma. 20. mai 12:05:43 +0200 2024]

**Comment by auanasgheps** [comment] 2024-05-21 07:21
@helangen yeah, after my last push in dev branch, the issue is on your side because the script is picking up an email address, but you did not configure it.

Please make sure you deleted all previous configurations and try again.

Honestly I don't know what could be causing this, maybe an old config file that the script is picking up.

I'll keep this open for a whule so you can keep us updated. In the meantime I'll release the fix version today :)

**Comment by helangen** [comment] 2024-05-21 07:44
Yeah, I have no clue what's causing this. As I said earlier, I configured an email the first time I set it up a few weeks ago but decided to switch to Discord. Then I set the email as blank (""), and after this it was still sending. It shouldn't store the email in other places than the config and I only have one config file in the folder where the script is. Anyways, I downloaded the dev branch (v3.3.2) and re-configured. Made sure there exists only one config file and script file in the folder.

**Comment by helangen** [comment] 2024-05-21 11:59
This is my output from todays run.

No sync is in progress.
The 52% of the array is not scrubbed.
You have 35 files with zero sub-second timestamp.
Run the 'touch' command to set it to a not zero value.
No rehash is in progress or needed.
No error detected.
```
curl: (22) The requested URL returned error: 400
All jobs ended. [ti. 21. mai 13:45:55 +0200 2024]
----------------------------------------
## Total time elapsed for SnapRAID: 3hrs 46min 54sec

I got an email today as well, but I think it has to do with my setup of root aliases in "/etc/aliases" on my server. There I have specified root: <email_address>. Does the script inform root in any way such that I get an email? Since the output from the log does not say that an email was sent?

**Comment by auanasgheps** [comment] 2024-05-29 10:35
Allright, then I'm going to close this!

**Closed by auanasgheps** 2024-05-29 10:35 UTC
Labels: bug

**Comment by helangen** [comment] 2024-05-29 17:41
> Allright, then I'm going to close this!

Yeah. I promise not to re-open 😝
